version: '3'

services:
  login-db:
    build:
      context: ./login-db
      dockerfile: Dockerfile
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - chat-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3

  login-app:
    build:
      context: ./login-app
      dockerfile: Dockerfile
    networks:
      - chat-network
    depends_on:
      login-db:
        condition: service_healthy

  chat-app:
    build:
      context: ./chat-app
      dockerfile: Dockerfile
    networks:
      - chat-network
    depends_on:
      - login-app

  nginx-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    networks:
      - chat-network
    depends_on:
      - chat-app
      - login-app

networks:
  chat-network:
