version: '3'

services:
  login-db:
    build:
      context: ./login-db
      dockerfile: Dockerfile
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - chat-network

  login-app:
    build:
      context: ./login-app
      dockerfile: Dockerfile
    networks:
      - chat-network
     depends_on:
      - login-db

  chat-app:
    build:
      context: ./chat-app
      dockerfile: Dockerfile
    networks:
      - chat-network
    depends_on:
      - login-app

  nginx-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    networks:
      - chat-network
    depends_on:
      - chat-app
      - login-app

networks:
  chat-network:
